### Problem statement
* we are given dataset of house prices with some features like no of bathrooms
  ,no of bedrooms etc.
* Our task is to create a model which will predict the price of any new house by
  looking at the features.
* While learning about machine learning it is best to actually work with real world
  data, not just artificial dataset.
* There are hundreds of open datasets to choose from. 

### Gatting started
* The first question i should ask to the client that what is the businees objective 
  and goal? How will dragon real estate benifit from the model?
* Client tell me that Dragon real estates will use this model to predict house
  prices in the given area and will invest in the area if its undervalued.
* Next question i should ask to the client is that how does the current solution look
  like? The answer is: Manual expert who analyze the features.
* The prediction made by so called "experts" are not very good( error rate is 25%)
  which is why dragon real estates pvt. ltd is counting on me

### Finding the type of model to built
* Supervised, unsupervised or reinforcement learning?- supervised
  bcoz we have target variable
* classification task or regression task?
  regression--bcoz target variable is quantitative
* batch learning or online learning techniques?
  batch learning- you already have data and you build a model on that data
  online learning- you have made a pipeline you are getting data continuously(on the fly)
  so its a batch learning. We already have data.

### Selecting a performence measure
* A typical performence measure for regression problem is root mean square error(RMSE)
* RMSE is generally the prefered performence measure for regression task,
  so we choose it for the perticular problem we are solving for Dragon real 
  estate Pvt. Ltd
* other performence measures include MAE,Manhattan norm, etc we will use RMSE 
  for this problem

### Checking the assumption
* it is very important to me to check for assumptions, I might have made and
  correct them before launching the ml system.
* For Example, I should make sure that team needs the price and not the 
  categories like expensive,cheap etc.
* If latter is the case, formulating the problem as a regression task will be
  counted as big mistake.
* i have talked to the dragon real estates team member and ensured that i am
  aware of all the assumptions.

## Dragon real estate price predictor

In [1]:
import pandas as pd

In [2]:
housing=pd.read_excel('data_housing.xlsx')

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing['CHAS'].value_counts()  # categorical variable

0    471
1     35
Name: CHAS, dtype: int64

In [6]:
housing['RAD'].value_counts()

24    132
5     115
4     110
3      38
6      26
2      24
8      24
1      20
7      17
Name: RAD, dtype: int64

In [7]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.287281   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705155   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.209000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.629000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [8]:
%matplotlib inline

In [9]:
import matplotlib.pyplot as plt

In [10]:
# housing.hist(bins=50,figsize=(20,15))
# plt.show()

In [11]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

### Train test splitting

In [12]:
import numpy as np


In [13]:
# def split_train_test(data,test_ratio):
#     np.random.seed(42)
#     shuffled =np.random.permutation(len(data))
#     test_set_size=int(len(data)*test_ratio)
#     test_indices=shuffled[:test_set_size]
#     train_indices=shuffled[test_set_size:]
#     return data.iloc[train_indices],data.iloc[test_indices]
    

In [14]:
# train_set, test_set=split_train_test(housing,0.2)

In [15]:
# print(f'rows in train set:{len(train_set)}\n rows in test set: {len(test_set)}\n')

In [16]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(housing,test_size=0.2,random_state=42)

In [17]:
from sklearn.model_selection import StratifiedShuffleSplit

In [18]:
split= StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing,housing['CHAS']):
    strat_train_set= housing.loc[train_index]
    strat_test_set= housing.loc[test_index]

In [19]:
housing= strat_train_set.copy()

In [20]:
strat_train_set

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
155  3.53501   0.0  19.58     1  0.871  6.152  82.6  1.7455    5  403   
423  7.05042   0.0  18.10     0  0.614  6.103  85.1  2.0218   24  666   
98   0.08187   0.0   2.89     0  0.445  7.820  36.9  3.4952    2  276   
455  4.75237   0.0  18.10     0  0.713  6.525  86.5  2.4358   24  666   
216  0.04560   0.0  13.89     1  0.550  5.888  56.0  3.1121    5  276   

     PTRATIO       B  LSTAT  MEDV  
254     16.4  392.89   6.57  21.9  
348     17.0  390.94   5.99  24.5  
476     20.2  396.21  18.68  16.7  
321     19.6  396.90   6.87  23.1  
326     19.6  396.90   6.15  23.0  
..       ...     ...    ...   ...  
155     14.7   88.01  15.02  15.6  
423     20.2    2.52  23.29  13.4  
98      18.0  393.53   3.57  43.8  
455     20.2   50.92  18.13  14.1  
216     16.4  392.80  13.51  23.3  

[404 rows x 14 columns]

In [21]:
strat_train_set.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.283173   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.716274   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.216000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.633000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  404.000000  404.000000  
mean    12.791609   22.509406  
std      7.235740    9.385531  
min      1.730000    5.000000  
25%      6.847500   16.600000  
50%     11.570000   21.150000  
75%     17.102500   25.000000  
max     36.980000   50.000000

In [22]:
strat_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 404 entries, 254 to 216
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     404 non-null    float64
 1   ZN       404 non-null    float64
 2   INDUS    404 non-null    float64
 3   CHAS     404 non-null    int64  
 4   NOX      404 non-null    float64
 5   RM       399 non-null    float64
 6   AGE      404 non-null    float64
 7   DIS      404 non-null    float64
 8   RAD      404 non-null    int64  
 9   TAX      404 non-null    int64  
 10  PTRATIO  404 non-null    float64
 11  B        404 non-null    float64
 12  LSTAT    404 non-null    float64
 13  MEDV     404 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 47.3 KB


In [23]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [24]:
strat_test_set['CHAS'].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

### looking for correlations

In [25]:
corr_matrix=housing.corr()

In [26]:
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.679496
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [27]:
# from pandas.plotting import scatter_matrix

# attributes=['MEDV','RM','ZN','LSTAT']
# scatter_matrix(housing[attributes],figsize=(12,8))
# plt.show()

In [28]:
# housing.plot(kind="scatter",x='RM',y='MEDV',alpha=0.8)

### Attribute combinations

In [29]:
housing['TAXRM']=housing['TAX']/housing['RM']

In [30]:
housing['TAXRM']

254     51.571709
348     42.200452
476    102.714374
321     45.012547
326     45.468948
          ...    
155     65.507152
423    109.126659
98      35.294118
455    102.068966
216     46.875000
Name: TAXRM, Length: 404, dtype: float64

In [31]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TAXRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [32]:
corr_matrix=housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.679496
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TAXRM     -0.527417
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [33]:
# housing.plot(kind="scatter",x='TAXRM',y='MEDV',alpha=0.8)

In [34]:
housing= strat_train_set.drop("MEDV",axis=1)
Housing_labels=strat_train_set['MEDV'].copy()

### Missing attributes

#### To take care of missing attributes you have 3 options:
    1. get rid of the missing datapoints--not valid options here
    2. get rid of the whole attribute- not valid options
    3. sat the value to zero,mean,median etc-- this is a valid option

In [35]:
#### options
a= housing.dropna(subset=['RM'])
a.shape    

(399, 13)

In [36]:
#### option 2
b=housing.drop('RM',axis=1)
b.shape

(404, 12)

In [37]:
### option3-compute median for option 3
median= housing['RM'].median()

In [38]:
median

6.216

In [39]:
housing['RM'].fillna(median)
housing.shape

(404, 13)

In [40]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')
imputer.fit(housing)

SimpleImputer(strategy='median')

In [41]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21600e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [42]:
imputer.statistics_.shape

(13,)

In [43]:
X= imputer.transform(housing)

In [44]:
housing_tr= pd.DataFrame(X, columns=housing.columns)

In [45]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.282342   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.711855   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.879750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.216000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

### Scikit_learn Design

#### Primarily, three types of objects:
    1. Estimater-- It estimates some parameter based on a dataset ex: imputer
        * it has a fit method and transform method.
          fitMethod- fits the dataset and calculate internal parameter
          Transform Method- Transform the parameter according to the calculation done by fit
        
    2. Transformers--transform method takes input and returns output based on the
       learnings from fit(). It also has a convenience function called fit_transform()
       which fits and then transform.
    3. Predictor- LinearRegression model is an example of predictior. fit()
    and predict() are two common functions. It also gives scores() function
    which will evaluate the predictions.

### feature scaling
Primerily , two types of feature scaling methods:
1. Min_max Scaling( Normalization)
          * value-min/(max-min)--- 0 to 1
          sklearn provies a class called MinMaxScaler for this
2. Standardization
          * value-mean/(std)---- 
          sklearn provies a class called StandardScaler for this  

### Creating pipeline

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline= Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    
    ('std_scaler', StandardScaler())
])

In [47]:
housing_num_tr=my_pipeline.fit_transform(housing)

In [48]:
housing_num_tr

array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

#### Selecting a desired model for Dragon Real Estates

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

model=LinearRegression()
model.fit(housing_num_tr,Housing_labels)

LinearRegression()

In [50]:
some_data = housing.iloc[:5]

In [51]:
some_labels=Housing_labels.iloc[:5]

In [52]:
prepare_data= my_pipeline.transform(some_data)

In [53]:
model.predict(prepare_data)

array([23.97075452, 27.23390521, 20.58226641, 25.01515072, 23.7360947 ])

In [54]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

### Evaluating the model

In [55]:
from sklearn.metrics import mean_squared_error
housing_predictions= model.predict(housing_num_tr)
lin_mse=mean_squared_error(Housing_labels, housing_predictions)
lin_rmse=np.sqrt(lin_mse)

In [56]:
lin_mse

23.339826084340054

In [57]:
lin_rmse

4.831130932229021

### Decision tree regressor

In [58]:
model1=DecisionTreeRegressor()

In [59]:
model1.fit(housing_num_tr,Housing_labels)
some_data1 = housing.iloc[:5]
some_labels1=Housing_labels.iloc[:5]
prepare_data1= my_pipeline.transform(some_data)
model1.predict(prepare_data1)
list(some_labels1)

[21.9, 24.5, 16.7, 23.1, 23.0]

In [60]:
from sklearn.metrics import mean_squared_error
housing_predictions= model1.predict(housing_num_tr)
mse=mean_squared_error(Housing_labels, housing_predictions)
rmse=np.sqrt(mse)

In [61]:
mse  # overfitting

0.0

### using batter evaluation technique-- cross validation

In [62]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model, housing_num_tr, Housing_labels, scoring='neg_mean_squared_error',cv=10)
rmse_scores1=np.sqrt(-scores)

In [63]:
rmse_scores1

array([4.21147237, 4.25826439, 5.11023239, 3.83895734, 5.34863397,
       4.37930618, 7.46815368, 5.4886771 , 4.14809627, 6.0599121 ])

In [64]:
scores1=cross_val_score(model1, housing_num_tr, Housing_labels, scoring='neg_mean_squared_error',cv=10)
rmse_scores=np.sqrt(-scores1)

In [65]:
rmse_scores

array([4.1376027 , 5.37305836, 5.27220045, 3.59213232, 4.05598323,
       3.16981861, 5.39504402, 3.906181  , 3.13926743, 4.49521968])

In [66]:
def print_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard Deviation:", scores.std())
    

In [67]:
print_scores(rmse_scores)

Scores: [4.1376027  5.37305836 5.27220045 3.59213232 4.05598323 3.16981861
 5.39504402 3.906181   3.13926743 4.49521968]
Mean: 4.253650780383021
Standard Deviation: 0.8172560660963621


In [68]:
print_scores(rmse_scores1)

Scores: [4.21147237 4.25826439 5.11023239 3.83895734 5.34863397 4.37930618
 7.46815368 5.4886771  4.14809627 6.0599121 ]
Mean: 5.031170580041596
Standard Deviation: 1.05872331973435


#### Random forest

In [69]:
from sklearn.ensemble import RandomForestRegressor

In [70]:
model2=RandomForestRegressor()
model2.fit(housing_num_tr,Housing_labels)

RandomForestRegressor()

In [71]:
some_data2 = housing.iloc[:5]
some_labels2=Housing_labels.iloc[:5]
prepare_data2= my_pipeline.transform(some_data2)
model1.predict(prepare_data2)
list(some_labels2)

[21.9, 24.5, 16.7, 23.1, 23.0]

In [78]:
scores2=cross_val_score(model2, housing_num_tr, Housing_labels, scoring='neg_mean_squared_error',cv=10)
rmse_scores2=np.sqrt(-scores2)

In [79]:
print_scores(rmse_scores2)

Scores: [2.81978676 2.88909757 4.31798045 2.64627031 3.35278919 2.48867326
 4.88233339 3.42902143 2.89401873 3.0068067 ]
Mean: 3.2726777786785997
Standard Deviation: 0.7271776673345621


#### Saving the model

In [80]:
from joblib import dump, load
dump(model,'Dragon.joblib')

['Dragon.joblib']

#### testing the model on test data

In [85]:
X_test=strat_test_set.drop('MEDV',axis=1)
Y_test=strat_test_set['MEDV'].copy()
X_test_prepared=my_pipeline.transform(X_test)
final_predictions=model.predict(X_test_prepared)
final_mse=mean_squared_error(Y_test, final_predictions)
final_rmse= np.sqrt(final_mse)
print(final_predictions, list(Y_test))

[22.66603654 17.22977545 30.00646771 30.72256362  8.80169751 13.2918085
 17.26309268 17.7488383  32.52124623 36.04157152 16.35960503  0.55826306
 22.98909222 20.46213989 20.01157258 12.94210378 31.17901222 13.37153196
 25.00106057 24.14443505 20.40196334 17.022256   17.8453079  25.58632355
 19.46627639 32.86154638 19.42916742 33.72941747  8.02802315 34.70441557
 19.51346083 21.45204829 29.29612216 16.35933872 26.98771449 18.36530251
 37.31234952 24.54335264 22.1810562  37.16915138 25.14094174 34.48449235
 23.45566631 24.0012322  18.49146998 32.70335895 38.45057388 21.36133689
 17.65718167 16.24235815 21.22354174 12.35851369 19.86968613 20.41013037
 27.93337986 33.06851554 40.10836695 31.38138796 14.94440683 19.70671431
 40.51189902 18.11781043 15.09532118 27.63835758 19.5000224  32.47850266
 23.41151756 20.31200511 21.16395136 33.81263059 34.12194633 27.61101925
 24.49631771 21.86435352 36.20751469  8.57965941 17.41959686 21.48849697
 20.51037079 22.97647909 25.96273787 22.52650094 14.

In [86]:
final_rmse

4.143804888366126

In [88]:
prepare_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24521527, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])